name: Base Debian Package Builder

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string
      url:
        required: true
        type: string
      arch:
        required: false
        type: string
        default: amd64
      install_path:
        required: false
        type: string
        default: /usr/local/bin

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev curl

      - name: Build Debian package
        run: |
          PACKAGE_DIR="packages/${{ inputs.name }}"
          mkdir -p "$PACKAGE_DIR"
          cd "$PACKAGE_DIR"

          # Download the file directly as the binary name
          BIN_NAME="${{ inputs.name }}"
          curl -L "${{ inputs.url }}" -o "$BIN_NAME"
          chmod +x "$BIN_NAME"

          # Create Debian package structure
          DEB_DIR="${{ inputs.name }}-${{ inputs.version }}"
          INSTALL_PATH="${{ inputs.install_path }}"
          mkdir -p "$DEB_DIR/DEBIAN" "$DEB_DIR$INSTALL_PATH"

          # Copy binary into package
          cp "$BIN_NAME" "$DEB_DIR$INSTALL_PATH/"

          # Create control file
          cat <<EOF > "$DEB_DIR/DEBIAN/control"
          Package: ${{ inputs.name }}
          Version: ${{ inputs.version }}
          Section: utils
          Priority: optional
          Architecture: ${{ inputs.arch }}
          Maintainer: Mirror Bot <mirror@githubactions.local>
          Description: ${{ inputs.name }} - mirrored package
          EOF

          # Build Debian package
          dpkg-deb --build "$DEB_DIR"

          # Move to public pool
          mkdir -p ../../../public/pool/main
          mv "$DEB_DIR.deb" ../../../public/pool/main/

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-${{ inputs.name }}
          path: public
