name: Build Debian Mirror

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev gnupg curl

      - name: Prepare repo structure
        run: |
          mkdir -p public/pool/main
          mkdir -p public/dists/stable/main/binary-amd64

      - name: Download fzf
        run: |
          mkdir -p build/fzf
          cd build/fzf
          curl -LO https://github.com/junegunn/fzf/releases/download/v0.65.1/fzf-0.65.1-linux_amd64.tar.gz
          tar -xzf fzf-0.65.1-linux_amd64.tar.gz

          # Make Debian package structure
          mkdir -p fzf-0.65.1/DEBIAN
          mkdir -p fzf-0.65.1/usr/local/bin
          cp fzf fzf-0.65.1/usr/local/bin/

          cat <<EOF > fzf-0.65.1/DEBIAN/control
          Package: fzf
          Version: 0.65.1
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: Mirror Bot <mirror@githubactions.local>
          Description: fzf - command-line fuzzy finder (mirrored package)
          EOF

          dpkg-deb --build fzf-0.65.1

          mkdir -p ../../public/pool/main/
          mv fzf-0.65.1.deb ../../public/pool/main/

      - name: Download packages
        run: |
          # TopTracker
          curl -L -o public/pool/main/toptracker_1.7.7-7583_amd64.deb \
            https://d101nvfmxunqnl.cloudfront.net/desktop/builds/debian/toptracker_1.7.7-7583_amd64.deb

          # Ghostty
          curl -L -o public/pool/main/ghostty_1.1.3-4_amd64.deb \
            https://download.opensuse.org/repositories/home:/clayrisser:/sid/Debian_Unstable/amd64/ghostty_1.1.3-4_amd64.deb

      - name: Generate Packages + Release
        run: |
          cd public
          dpkg-scanpackages --arch amd64 pool/main > dists/stable/main/binary-amd64/Packages
          gzip -k dists/stable/main/binary-amd64/Packages

          cat > apt-ftparchive.conf <<EOF
          APT::FTPArchive::Release {
            Origin "amrography";
            Label "amrography";
            Suite "stable";
            Codename "stable";
            Architectures "amd64";
            Components "main";
          };
          EOF

          apt-ftparchive -c=apt-ftparchive.conf release dists/stable > dists/stable/Release

      - name: GPG Sign Release
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --batch --yes --pinentry-mode loopback -abs \
            -o public/dists/stable/Release.gpg public/dists/stable/Release
          gpg --batch --yes --pinentry-mode loopback --clearsign \
            -o public/dists/stable/InRelease public/dists/stable/Release

      - name: Export Public Key
        run: |
          gpg --export -a > public/amrography-debian.gpg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
