name: Build Debian Mirror

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev gnupg curl

      - name: Prepare repo structure
        run: |
          mkdir -p public/pool/main
          mkdir -p public/dists/stable/main/binary-amd64

      - name: Download packages
        run: |
          # TopTracker
          curl -L -o public/pool/main/toptracker_1.7.7-7583_amd64.deb \
            https://d101nvfmxunqnl.cloudfront.net/desktop/builds/debian/toptracker_1.7.7-7583_amd64.deb

          # Ghostty
          curl -L -o public/pool/main/ghostty_1.1.3-4_amd64.deb \
            https://download.opensuse.org/repositories/home:/clayrisser:/sid/Debian_Unstable/amd64/ghostty_1.1.3-4_amd64.deb

      - name: Generate Packages + Release
        run: |
          cd public
          dpkg-scanpackages --arch amd64 pool/main > dists/stable/main/binary-amd64/Packages
          gzip -k dists/stable/main/binary-amd64/Packages

          apt-ftparchive release dists/stable > dists/stable/Release

      - name: GPG Sign Release
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --batch --yes --pinentry-mode loopback -abs \
            -o public/dists/stable/Release.gpg public/dists/stable/Release
          gpg --batch --yes --pinentry-mode loopback --clearsign \
            -o public/dists/stable/InRelease public/dists/stable/Release

      - name: Export Public Key
        run: |
          gpg --export -a > public/amrography-debian.gpg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
