name: Build Debian Mirror

on:
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
  branches:
    - main
  workflow_dispatch:

permissions:
  contents: write   # needed for gh-pages push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:13

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y git curl dpkg-dev gnupg jq apt-transport-https apt-utils

      - name: Import GPG private key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Download packages
        run: |
          mkdir -p public/pool/main
          cd public/pool/main

          # TopTracker
          curl -L -o toptracker_1.7.7-7583_amd64.deb \
            https://d101nvfmxunqnl.cloudfront.net/desktop/builds/debian/toptracker_1.7.7-7583_amd64.deb

          # Ghostty (fetch latest amd64 .deb from OBS)
          GHOSTTY_URL=$(curl -s https://download.opensuse.org/repositories/home:/clayrisser:/sid/Debian_Unstable/amd64/ \
            | grep -oP "ghostty_[0-9]+\.[0-9]+\.[0-9]+-[0-9]+_amd64\.deb" \
            | sort -V | tail -n1)

          if [ -z "$GHOSTTY_URL" ]; then
            echo "❌ Could not find Ghostty .deb in OBS repo"
            exit 1
          fi

          echo "✅ Found Ghostty package: $GHOSTTY_URL"
          curl -L -o "$GHOSTTY_URL" "https://download.opensuse.org/repositories/home:/clayrisser:/sid/Debian_Unstable/amd64/$GHOSTTY_URL"

      - name: Build APT repo structure
        run: |
          mkdir -p public/dists/stable/main/binary-amd64
          dpkg-scanpackages --arch amd64 public/pool /dev/null > public/dists/stable/main/binary-amd64/Packages
          gzip -9c public/dists/stable/main/binary-amd64/Packages > public/dists/stable/main/binary-amd64/Packages.gz

          cat > public/dists/stable/Release <<EOF
          Origin: amrography
          Label: amrography
          Suite: stable
          Codename: stable
          Architectures: amd64
          Components: main
          Description: Custom Debian repo
          EOF

      - name: Sign repo metadata
        run: |
          cd public/dists/stable
          gpg --batch --yes -abs -o Release.gpg Release
          gpg --batch --yes --clearsign -o InRelease Release
          cd ../../..

      - name: Export public key
        run: |
          gpg --armor --export > public/amrography-debian.gpg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
