name: Build Debian Mirror

on:
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write   # needed for gh-pages push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:13

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y git curl dpkg-dev gnupg jq apt-transport-https apt-utils

      - name: Import GPG private key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Download packages
        run: |
          mkdir -p pool/main
          cd pool/main

          # TopTracker
          curl -L -o toptracker_1.7.7-7583_amd64.deb \
            https://d101nvfmxunqnl.cloudfront.net/desktop/builds/debian/toptracker_1.7.7-7583_amd64.deb

          # Ghostty (using clayrisser repo builds)
          curl -L -o ghostty_latest_amd64.deb \
            https://github.com/clayrisser/debian-ghostty/releases/latest/download/ghostty_amd64.deb

      - name: Build APT repo structure
        run: |
          mkdir -p dists/stable/main/binary-amd64
          dpkg-scanpackages --arch amd64 pool /dev/null > dists/stable/main/binary-amd64/Packages
          gzip -9c dists/stable/main/binary-amd64/Packages > dists/stable/main/binary-amd64/Packages.gz

          cat > dists/stable/Release <<EOF
          Origin: amrography
          Label: amrography
          Suite: stable
          Codename: stable
          Architectures: amd64
          Components: main
          Description: Custom Debian repo
          EOF

      - name: Sign repo metadata
        run: |
          cd dists/stable
          gpg --batch --yes -abs -o Release.gpg Release
          gpg --batch --yes --clearsign -o InRelease Release
          cd ../..

      - name: Export public key
        run: |
          gpg --armor --export > myrepo.gpg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
