name: Build Debian Mirror

on:
  push:
    branches: ['main']

jobs:
  # build-fzf:
  #   uses: ./.github/workflows/packages/package-fzf.yml

  # build-ghostty:
  #   needs: build-fzf
  #   uses: ./.github/workflows/packages/package-ghostty.yml

  package-workflows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['package-fzf.yml', 'package-ghostty.yml']
    steps:
      - name: Trigger package workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: ${{ matrix.package }}
          ref: main

  generate-release:
    # needs: [build-fzf, build-ghostty]
    needs: [package-workflows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Packages + Release
        run: |
          cd public
          dpkg-scanpackages --arch amd64 pool/main > dists/stable/main/binary-amd64/Packages
          gzip -k dists/stable/main/binary-amd64/Packages

          cat > apt-ftparchive.conf <<EOF
          APT::FTPArchive::Release {
            Origin "amrography";
            Label "amrography";
            Suite "stable";
            Codename "stable";
            Architectures "amd64";
            Components "main";
          };
          EOF

          apt-ftparchive -c=apt-ftparchive.conf release dists/stable > dists/stable/Release

      - name: GPG Sign Release
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --batch --yes --pinentry-mode loopback -abs \
            -o public/dists/stable/Release.gpg public/dists/stable/Release
          gpg --batch --yes --pinentry-mode loopback --clearsign \
            -o public/dists/stable/InRelease public/dists/stable/Release

      - name: Export Public Key
        run: gpg --export -a > public/amrography-debian.gpg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
